M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu20.04.1} date Wed 02 Aug 2023 11:15:24 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-02T11:15:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X28.555Y-82.06
X28.555Y-87.84
T0
M30
